version: 2

sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
