name: Formatting check
on:
- pull_request

jobs:
  black-pylint:
    if: github.event.pull_request.draft == false
    needs: [determine_runner]
    runs-on: ${{ needs.determine_runner.outputs.runner_group }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install black pylint==3.3.7 isort==6.0.1

      - uses: actions/checkout@v4

      - name: Run Black
        run: |
          black -t py311 -t py312 -t py313 -l 100 pennylane_qiskit/ --check
          black -t py311 -t py312 -t py313 -l 100 tests/ --check

      - name: Run isort
        run: |
          isort --py 312 --profile black -l 100 -o autoray -p ./pennylane_qiskit --skip __init__.py --filter-files ./pennylane_qiskit --check
          isort --py 312 --profile black -l 100 -o autoray -p ./pennylane_qiskit --skip __init__.py --filter-files ./tests --check

      - name: Run Pylint (source files)
        if: always()
        run: pylint --rcfile .pylintrc $(find pennylane_qiskit -name "*.py")

      - name: Run Pylint (test files)
        if: always()
        run: pylint --rcfile tests/.pylintrc $(find tests -name "*.py")
